//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjPortadorSindromeIrlen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parceiros
    {
        public int IdParceiro { get; set; }
        public string Parceiros1 { get; set; }
        public string Logo { get; set; }
        public string Mensagem { get; set; }
    }
}
