//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjPortadorSindromeIrlen
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuemSomos
    {
        public int IdQuemSomos { get; set; }
        public string Historia { get; set; }
        public string Objetivos { get; set; }
        public string Valores { get; set; }
        public string Foto { get; set; }
    }
}
